package RoleSystem;

public enum Authority{
	URUNLERI_GORUNTULE,
	URUN_YONET,
	URUN_SATINAL,
	SEPET_GORUNTULE,
	BILGILERIMI_GORUNTULE, 
	DEPO_YONET, 
	DEPOLARI_GORUNTULE,
	CALISANLARI_YONET, 
	KULLANICILARI_YONET,
	TEDARIKCILERI_YONET, 
	KARGOFIRMASI_YONET,
	URUN_KABULETME, 
	MUSTERISIPARIS_GORUNTULE, 
	KURYESIPARIS_GORUNTULE,
	LOGKAYITLARI_GORUNTULE
}
